### ISSUE TITLE
how the fuck do i use this

### ISSUE THREAD

**Issue by imightknoiw** [DxltaMath/dGUI#1]
pls

**Comment by afkvido** [comment]
@imightknoiw see this: https://github.com/DxltaMath/DMIx#readme

if ur using chrome then just get this: https://chrome.google.com/webstore/detail/delta-math-interception-e/lhhhbaakoallicbipmckclbigdlkdodh
and then load deltamath as usual, you should see a hack arrow in the top left corner

**Comment by JackWagon885** [comment]
DMIx doesn't work anymore.
Makes my life harder.

**Comment by afkvido** [comment]
@JackWagon885 if it makes your life harder not having DMIX, you been misusing it, read the Readme.md

**Comment by afkvido** [comment]
ye ye the big warning sign in all caps
