### ISSUE TITLE
Not an issue with the hack itself but rather information on it

### ISSUE THREAD

**Issue by JackWagon885** [DxltaMath/dGUI#2]
Being a novice hack installationer, I have NO idea how to install this. I tried checking the closed forum of the same issue, but it didn't tell me anything. I tried installing this as an extension, but it just says "Manifest file is missing or unreadable". How do I install this hack? If it helps, I'm on Edge.

(also put it in the read me)

**Comment by afkvido** [comment]
It's been years since I've touched the code of this extension, it's probably deprecated, and I currently have no plans to fix it in the near future, as I've been very busy.

Sorry mate

**Comment by JackWagon885** [comment]
oh ok
